### ISSUE TITLE
Problem with AccessIS ID and passport scan

### ISSUE THREAD

**Issue by mcghorayeb** [Coppernic/mrz-parser#6]
When I scan a French ID with the AccessIS on cOne e-id, I get this error:
Input ID MRZ (transcribed by hand):
```
IDFRAREYNIER<<<<<<<<<<<<<<<<<<013029
2101133537444MICHAEL<<DENIS8406273M3
```
---
Output error:
```
2021-10-13 14:36:12.903 9912-9912/fr.coppernic.app.id W/System.err: fr.coppernic.lib.mrz.model.MrzParserException: Wrong format Not enough lines (1)
2021-10-13 14:36:12.904 9912-9912/fr.coppernic.app.id W/System.err:     at fr.coppernic.lib.mrz.MrzParser.getFormat$mrz(MrzParser.kt:45)
2021-10-13 14:36:12.904 9912-9912/fr.coppernic.app.id W/System.err:     at fr.coppernic.lib.mrz.MrzParser.parseLines(MrzParser.kt:31)
2021-10-13 14:36:12.904 9912-9912/fr.coppernic.app.id W/System.err:     at fr.coppernic.lib.mrz.MrzParser.parse(MrzParser.kt:19)
2021-10-13 14:36:12.905 9912-9912/fr.coppernic.app.id W/System.err:     at fr.coppernic.lib.mrz.MrzParser.parse$default(MrzParser.kt:18)
2021-10-13 14:36:12.905 9912-9912/fr.coppernic.app.id W/System.err:     at fr.coppernic.app.id.interactors.ocr.physical.MrzOcrInteractor.listen$lambda-0(MrzOcrInteractor.kt:35)
2021-10-13 14:36:12.905 9912-9912/fr.coppernic.app.id W/System.err:     at fr.coppernic.app.id.interactors.ocr.physical.MrzOcrInteractor.lambda$nKLOh7uu-0eZ3m5yPsk5crYFLX8(Unknown Source:0)
2021-10-13 14:36:12.905 9912-9912/fr.coppernic.app.id W/System.err:     at fr.coppernic.app.id.interactors.ocr.physical.-$$Lambda$MrzOcrInteractor$nKLOh7uu-0eZ3m5yPsk5crYFLX8.apply(Unknown Source:4)
2021-10-13 14:36:12.905 9912-9912/fr.coppernic.app.id W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
2021-10-13 14:36:12.906 9912-9912/fr.coppernic.app.id W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:66)
2021-10-13 14:36:12.906 9912-9912/fr.coppernic.app.id W/System.err:     at fr.coppernic.lib.interactors.ocr.AccessIsInteractor$mrzListener$1.onMrz(AccessIsInteractor.kt:95)
2021-10-13 14:36:12.906 9912-9912/fr.coppernic.app.id W/System.err:     at fr.coppernic.sdk.ocr.impl.ListenerDecorated$3.run(ListenerDecorated.java:47)
2021-10-13 14:36:12.906 9912-9912/fr.coppernic.app.id W/System.err:     at android.os.Handler.handleCallback(Handler.java:790)
2021-10-13 14:36:12.906 9912-9912/fr.coppernic.app.id W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-10-13 14:36:12.907 9912-9912/fr.coppernic.app.id W/System.err:     at android.os.Looper.loop(Looper.java:164)
2021-10-13 14:36:12.907 9912-9912/fr.coppernic.app.id W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6518)
2021-10-13 14:36:12.907 9912-9912/fr.coppernic.app.id W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-10-13 14:36:12.907 9912-9912/fr.coppernic.app.id W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2021-10-13 14:36:12.907 9912-9912/fr.coppernic.app.id W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Same error returned after scanning a passport (In my case echantillion B)

**Comment by mcghorayeb** [comment]
> Qu'est-ce que l'intéracteur OCR envoie comme string exactement ?
> 
> Est-ce qu'il y aurait un replace('\n','') en qq part ?

Je vais essayer de trouver cela
